### ISSUE TITLE
Game crashes when launching on 1.20.4 (mod version 1.0.1.)

### ISSUE THREAD

**Issue by swaggy111** [KKW557/MoreCursors#1]
when i try to launch minecraft with the mod installed in 1.20.4, the game crashes
heres the error code:
![Capture](https://github.com/KKW557/MoreCursors/assets/175113066/716549a5-c5c5-47bd-a32e-0921431ab05a)

**Comment by KKW557** [comment]
This mod is build on java21, now u only use java21 can load. I will build a version of java 17 later

**Comment by KKW557** [comment]
[v1.0.2](https://github.com/KKW557/MoreCursors/releases/tag/v1.0.2)
