### ISSUE TITLE
mod still isnt working with 1.20.4 with the latest version

### ISSUE THREAD

**Issue by swaggy111** [KKW557/MoreCursors#3]
i installed the mod that supports java 17, but instead it shows up with a different error. it says i need a different version of fabric loader, but i already have the latest version and it does not show what version i need
![Capture](https://github.com/KKW557/MoreCursors/assets/175113066/586171ed-e776-4dfc-a53f-6bf603a2f458)

**Comment by KKW557** [comment]
Check ur mod file name contains "source"? use no "source" file. Or go modrinth download new version.

**Comment by KKW557** [comment]
Check ur mod file name contains "source"? use no "source" file. Or go modrinth download new version.

**Comment by swaggy111** [comment]
i downloaded the one without the source in the name (MoreCursors-1.0.2.jar). i tried it and it shows up a different error.
![Capture](https://github.com/KKW557/MoreCursors/assets/175113066/76fef1aa-6a66-4742-bd1c-b2fa4e0bf438)

**Comment by KKW557** [comment]
Mixin required 21 that wrong mixins.json, fixed on [v1.0.3](https://github.com/KKW557/MoreCursors/releases/tag/v1.0.3)

**Comment by KKW557** [comment]
Mixin required 21 that wrong mixins.json, fixed on [v1.0.3](https://github.com/KKW557/MoreCursors/releases/tag/v1.0.3)
